POST   http://localhost:3000/admin/addDoctor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsImlhdCI6MTYxNzIwNzIyMX0._QjOmSUUGSj6OZpKVx_ZywWeLRb6iOyks5UM8EzuBGA
Content-Type: application/json

{
"username":"doctor3",
"password":"doctor",
"firstname" : "doctor",
"lastname" : "doctor"
}


###
POST http://localhost:3000/admin/addAdmin
Content-Type: application/json

{
"id":1,
"username":"Admin",
"password":"Admin123",
"firstname" : "Admin",
"lastname" : "Admin"

}
###
POST http://localhost:3000/admin/addAdmin
Content-Type: application/json


{"username":"mouadh",
"password":"test456",
"firstname" : "mouadh",
"lastname" : "gnichi"
}
####

POST http://localhost:3000/admin/login
Content-Type: application/json

{"username":"Admin",
"password":"Admin123"
}
###
POST http://localhost:5000/admin/addAdmin
Content-Type: application/json

{
"id":2,
"username":"Admin3",
"password":"Admin123",
"firstname" : "Admin",
"lastname" : "Admin"

}